apiVersion: v1
kind: Pod
metadata:
  name: python-and-cpp-example
  namespace: dev
spec:
  containers:
  - name: main-container
    image: 43034r/python_and_cpp_example:main
    volumeMounts:
    - name: app-volume
      mountPath: /app
  initContainers:
  - name: downloader
    image: alpine/git
    args:
    - clone
    - --single-branch
    - --branch=main
    - https://github.com/43034r/Python_and_cpp_example.git
    - /source
    volumeMounts:
    - name: app-volume
      mountPath: /source
  - name: builder
    image: gcc:latest
    command: ['sh', '-c', 'g++ -static /source/fibonacci.cpp -o /source/fibonacci && ls | grep -v "fibonacci" | xargs rm && cp /source/fibonacci /app']
    volumeMounts:
    - name: app-volume
      mountPath: /source
  volumes:
  - name: app-volume
    emptyDir: {}

